title: "Dr. Anitha Mekala"
email: "your.email@example.com"
description: >-
  PhD in MEMS, passionate about micro-systems, vibrations, and smart sensors.
baseurl: ""
url: "https://yourusername.github.io"
